version: 2
jobs:
  build:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    steps:
      - checkout
      - run: go build ./...
  test:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    environment:
      GLOG_logtostderr: '1'
    steps:
      - checkout
      - run: go test -race -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)
  node_test:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    steps:
      - checkout
      - run: go mod vendor
      - run: >
          . $HOME/.nvm/nvm.sh &&
          cd examples/browser &&
          npm install gulp-cli &&
          npm install &&
          ./node_modules/.bin/gulp
  generate:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    steps:
      - checkout
      - run: make realclean
      - run: make examples SWAGGER_CODEGEN="${SWAGGER_CODEGEN}" # Set in Docker image
      - run: go mod tidy
      - run: git diff --exit-code
  lint:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: make lint
  release:
    docker:
      - image: jfbrandhorst/grpc-gateway-build-env:1.12
    working_directory: /src/grpc-gateway
    steps:
      - checkout
      - run: go mod vendor
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  all:
    jobs:
      - build
      - test
      - node_test
      - generate
      - lint
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
